# Generated by Django 2.2.2 on 2019-08-10 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogger', models.CharField(max_length=255, verbose_name='Blogger')),
                ('evaluation', models.IntegerField(default=0, verbose_name='Evaluation')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='Last modify')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'unique_together': {('author', 'blogger')},
            },
        ),
    ]
